### ISSUE TITLE
ask for the configuration of environment

### ISSUE THREAD

**Issue by DDBarBar** [ChanganVR/CADRL#1]
I want to implement your source program ,but some errors appear.So,could you provide me with your configuration of environment.Thank you so much.

**Comment by ChanganVR** [comment]
Thank you for your interests! But this library is no longer maintained. CADRL and GA3C-CADRL is also implemented in our newest library [CrowdNav](https://github.com/vita-epfl/CrowdNav),
which is easier to use and can be better used for benchmarking RL navigation algorithms.
